# Linter Rules
include: package:effective_dart/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  enable-experiment:
    - non-nullable

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
